export const github: string;
export const item: string;
export const link: string;
export const list: string;
export const logo: string;
export const twitter: string;
export const works: string;
export const worksText: string;
export const zenn: string;
